urls.py
from django.urls import path

from . import views

app_name = 'ppclp'

urlpatterns = [
    path('page/<int:pk>', views.PageDisplay.as_view(), name='page-display'),
    path('page/<int:pk>/placement/<int:placement_pk>', views.PageDisplay.as_view(), name='placement-display'),
    path('page/<int:pk>/edit', views.PageUpdate.as_view(), name='page-update'),

]

models.py
from django.db import models

class Page(models.Model):
    name = models.CharField(
        "name",
        max_length=50,
        help_text="The name of the page"
    )
    slug = models.SlugField(
        "slug",
        unique=True,
        help_text="The URL slug"
    )
    cover_photo = models.ImageField(
        "Cover Photo",
        null=True,
        blank=True,
        help_text='The cover photo for this page'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Element(models.Model):
    title = models.CharField(
        max_length=100,
        blank=True,
        help_text = 'The text of the headline for this elememnt'
    )
    content = models.TextField(
        "content",
        blank=True,
        help_text='The content of the block'
    )
    date_modified = models.DateField(
        auto_now=True,
        help_text='The date of last modification'
    )

    def __str__(self):
        if len(self.title) > 75:
            return self.title[:70] + ' ...'
        else:
            return self.title

    class Meta:
        ordering = ['title']

class Placement(models.Model):
    page = models.ForeignKey(
        Page,
        on_delete=models.CASCADE
    )
    element = models.ForeignKey(
        Element,
        on_delete=models.CASCADE
    )
    order = models.IntegerField(
        "order",
        default=0,
        help_text = 'The order in which this element appears on the page'
    )
    level = models.PositiveSmallIntegerField(
        "level",
        default=2,
        choices=((2,"h2"), (3,"h3"),(4,"h4"),(5,"h5"),(6,"h6")),
        help_text = 'The heading level of this element, corresponding to the html tags &lt;h2&gt; - &lt;h6&gt;.  Only use 2 - 6.  &lt;h1&gt; is used for the page title. '
    )
    is_hidden = models.BooleanField(
        "hidden",
        default=False,
        help_text="If this placement should not appear in the menubar or in the listing of all elements."
    )

    def __str__(self):
        element = self.element.__str__() if hasattr(self, 'element') else ''
        page = self.page.__str__() if hasattr(self,'page') else ''

        full_str = '%s on %s' % (element, page )
        if len(full_str) > 75:
            return full_str[:70] + ' ...'
        else:
            return full_str

    class Meta:
        ordering = ['page', 'order']

forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Project, ProjectNote, Technician

class ProjectForm(forms.ModelForm):
    def __init__(self, **kwargs):
        return super().__init__(**kwargs)

    class Meta:
        model = Project
        fields = [
            'page',
            'slug',
        ]
        widgets = {
            'title':forms.TextInput(attrs={'class':'widthlong'}),
            'description':forms.Textarea(attrs={'class':'widthlong'}),
            'begin':forms.DateTimeInput(format='%Y-%m-%dT%H:%M:%S',  attrs={'type':'datetime-local'} ),

        }


ProjectProjectNoteFormset = inlineformset_factory(Project, ProjectNote, form=ProjectProjectNoteForm, extra=10)

views.py
from django import views
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.shortcuts import render
from django.http import HttpResponse
from .models import Element, Page, Placement
import markdown
from django.contrib.auth.mixins import PermissionRequiredMixin

class PageDisplay(DetailView):
    model = Page
    template_name = 'ppclp/page_display.html'

    def process_content(self, placement):
        content = '<div class="content-block">' + markdown.markdown(placement.element.content) + '</div>'

        #Push down heading levels within the content so a heading within content is lower than the heading
        #of the element.  So if the elemnent is level 2, then title is enclosed in h2 tags, and the following code
        #converts h1 tags in the content to h3
        for i in range(6,0,-1):
            for header_tag in ['<h', '</h']:

                header_level = i + placement.level
                header_level_str = str(header_level)
                i_str = str(i)

                if header_level > 6:
                    if header_tag == '<h':
                        content = content.replace(header_tag + i_str + '>', '</div><h6 class="h' + header_level_str + '">')
                    else:
                        content = content.replace(header_tag + i_str + '>', '</h6><div class="content-block">')  
                else:
                    if header_tag == '<h':
                        content = content.replace(header_tag + i_str + '>', '</div>' + header_tag + header_level_str + '>')
                    else:
                        content = content.replace(header_tag + i_str + '>', header_tag + header_level_str + '><div class="content-block">')

        subplacements = placement.page.placement_set.filter(order__gt=placement.order).filter(is_hidden=placement.is_hidden)
        if subplacements.exists():
             if subplacements.first().level == placement.level + 1:
                for subplacement in subplacements:
                    if subplacement.level <= placement.level:
                        break
                    if subplacement.level == placement.level + 1 and subplacement.is_hidden == placement.is_hidden:
                        print('tp2281e31')
                        print('tp2281e32', placement)
                        print('tp2281e33', subplacement)
                        sp_level = str(subplacement.level)
                        content = content + '<h' + sp_level + '>' + subplacement.element.title + '</h' + sp_level + '>'
                        content = content + self.process_content(subplacement)

        return content


    def get_context_data(self, **kwargs):
        
        context_data = super().get_context_data(**kwargs)
        all_placements = self.object.placement_set.all()
        context_data['placements'] = []
        context_data['menu_items'] = []

        context_data['chosen_placement'] = 0
        if 'placement_pk' in self.kwargs:
            print('tp2281e43', self.kwargs.get('placement_pk'))
            context_data['chosen_placement'] = self.kwargs.get('placement_pk')

        for placement in all_placements:
            if not placement.is_hidden:
                context_data['menu_items'].append(placement)

            if ( placement.level == 2 and context_data['chosen_placement'] == 0 and not placement.is_hidden ) or placement.pk == context_data['chosen_placement']:
                placement.element.content = self.process_content(placement)
                context_data['placements'].append(placement)

        return context_data
        

class PageUpdate(PermissionRequiredMixin, UpdateView):
    permission_required='change_page'
    model = Page
    template_name = 'ppclp/page_form.html'
    

    def get_context_data(self, **kwargs):
        
        context_data = super().get_context_data(**kwargs)
        context_data['page'] = self.form.object
        all_placements = self.object.placement_set.all()
        context_data['placements'] = []
        context_data['menu_items'] = []

        context_data['chosen_placement'] = 0
        if 'placement_pk' in self.kwargs:
            print('tp2281e43', self.kwargs.get('placement_pk'))
            context_data['chosen_placement'] = self.kwargs.get('placement_pk')

        for placement in all_placements:
            if not placement.is_hidden:
                context_data['menu_items'].append(placement)

            if ( placement.level == 2 and context_data['chosen_placement'] == 0 and not placement.is_hidden ) or placement.pk == context_data['chosen_placement']:
                placement.element.content = self.process_content(placement)
                context_data['placements'].append(placement)

        return context_data
        

templates/ppclp/_base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Suffolk Public Library Public PC Landing Page</title>
		<link rel="stylesheet" href="{% static 'ppclp/ppclp.css' %}">
		<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Nunito:300,600,700,800,italic,regular|Nunito+Sans:300,600,700,regular|" media="all">
	</head>
	<body>
		<div id="div_header">
			{% comment %} <img src="{% static 'ppclp/ppclp_banner.png' %}">{% endcomment %}
			<img src="{{ page.cover_photo.url }}">
		</div>
		<h1>Suffolk Public Library Public PC: {% block pagename %}{% endblock %}</h1>
		<div id="div_sidebar">
		{% block sidebar %}
		{% endblock %}
		</div>
		<div id="div_content">
		{% block content %}
		{% endblock %}
		</div>
	</body>
</html>

templates/ppclp/page_display.html
{% extends './_base.html' %}
{% load touglates_tags %}
{% block pagename %}{{ page }}{% endblock %}
{% block sidebar %}
<div class="sidemenu_item">
    <a href="{% url 'ppclp:page-display' object.pk %}">All Items</a>
</div>
{% for menu_item in menu_items %}
    <div class="sidemenu_item">
        <a href="{% url 'ppclp:placement-display' object.pk menu_item.pk %}"  class="menu_item_level_{{ menu_item.level }}" {% if chosen_placement.pk == menu_item.pk %} class="chosen"{% endif %} >{{ menu_item.element.title }}</a>
    </div>
{% endfor %}
{% endblock %}
{% block content %}

    {% for placement in placements %}


        <div class="placement">
            <h{{ placement.level }}>{{ placement.element.title }}</h{{ placement.level }}>
            {{ placement.element.content | safe }}
        </div>

    {% endfor %}
{% endblock %}

templates/ppclp/page_form.html
{% extends './_base.html' %}
{% load touglates_tags %}
{% block pagename %}{{ page }}{% endblock %}
{% block sidebar %}
<div class="sidemenu_item">
    <a href="{% url 'ppclp:page-display' object.pk %}">All Items</a>
</div>
{% for menu_item in menu_items %}
    <div class="sidemenu_item">
        <a href="{% url 'ppclp:placement-display' object.pk menu_item.pk %}"  class="menu_item_level_{{ menu_item.level }}" {% if chosen_placement.pk == menu_item.pk %} class="chosen"{% endif %} >{{ menu_item.element.title }}</a>
    </div>
{% endfor %}
{% endblock %}
{% block content %}

    {% for placement in placements %}

        <div class="placement">
            <h{{ placement.level }}>{{ placement.element.title }}</h{{ placement.level }}>
            {{ placement.element.content | safe }}
        </div>

    {% endfor %}
{% endblock %}